spring.application.name=demo

# Ollama chat model configuration
smartstudy.ollama.base-url=http://localhost:11434
smartstudy.ollama.model-name=granite3.2-vision:2b

# Ollama embedding model configuration (used by EmbeddingModel bean)
smartstudy.ollama.embedding-model-name=nomic-embed-text:latest

# Tavily API key for web search integration
smartstudy.tavily.api-key=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
